### ISSUE TITLE
Add option to open path

### ISSUE THREAD

**Issue by aprilkenopsia** [drakonkat/webtorrent-express-api#2]
**Add a fast and simple way to open torrents path**
It would be useful to be able to just click the torrent you have downloaded and go to its folder, as of right now is confusing (at least to me) to get to its path

unsure about how it could be done, maybe with a button on the action side?
![image](https://user-images.githubusercontent.com/28115928/175788089-74681cd9-41dc-4122-af60-be68537d1497.png)

**Comment by drakonkat** [comment]
Good idea, i will add it for sure in the next release

**Comment by drakonkat** [comment]
I have added it with the release 1.7.3
