### ISSUE TITLE
White screen when starting on linux

### ISSUE THREAD

**Issue by a8underscore** [drakonkat/webtorrent-express-api#3]
**Describe the bug**
White screen when starting on linux
<img width="869" alt="image" src="https://user-images.githubusercontent.com/60801647/176980189-7369cb9d-b736-4b4d-a38d-aca73d09de92.png">

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Version [e.g. 22] 1.7.2 appimage

**Comment by drakonkat** [comment]
Thanks, I have to find a way to reproduce the problem, hopefully I'll have time in the next period.

**Comment by drakonkat** [comment]
> **Describe the bug** White screen when starting on linux <img alt="image" width="869" src="https://user-images.githubusercontent.com/60801647/176980189-7369cb9d-b736-4b4d-a38d-aca73d09de92.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: Gentoo
> * Version [e.g. 22] 1.7.2 appimage

Is possible for you attach the complete log from the console?

**Comment by a8underscore** [comment]
https://paste.gg/p/anonymous/3a696b01be854400aaa3509838f7d199

**Comment by drakonkat** [comment]
I'm trying to reproduce the case on ubuntu, and fix it. 
But basically the software cannot create the file:
![image](https://user-images.githubusercontent.com/17176640/180716822-9f62cc69-797b-43f7-b4cb-d31eaa1dfd00.png)

To fix before any update i think you can try:
- Create a void file "LOCK", it can be done with touch command or from the GUI
- Or try to run the software as "sudo" and see if the file will be created


In any case i hope to fix it soon :)

**Comment by drakonkat** [comment]
I have installed some Linux based OS to replicate the problem. 
Sometimes gives me the problem because a known issue of a dependency. I tried to apply the official workaround described in the docs and seems to resolve on my test.

Can you try the latest version [1.7.4](https://github.com/drakonkat/Crawfish/releases/tag/v1.7.4)?

**Comment by drakonkat** [comment]
Stale
