### ISSUE TITLE
Bug with typing "-1" in textboxes

### ISSUE THREAD

**Issue by Chupakabra0** [drakonkat/webtorrent-express-api#4]
**Describe the bug**
Impossible to write "-" in such textboxes like "Download speed" and "Upload speed"

**To Reproduce**
1. Go to Settings > General
2. Clean "Download Speed" textbox
3. Try to write "-" and "1"
4. 'Cause "-" is validation fail, it won't be written

To avoid this problem user need to type any number, go to begin of the textbox and type "-". It seems to be non-intuitive.

**Desktop:**
 - OS: Windows 11 Pro
 - Version 21H2

**Comment by drakonkat** [comment]
I'll add a check box for unlimited speed, I assume, will be more intuitive.

**Comment by drakonkat** [comment]
I have added a checkbox to enable the "unlimited" speed
