### ISSUE TITLE
Idea: Support of optionally not downloading a file

### ISSUE THREAD

**Issue by fusir** [drakonkat/webtorrent-express-api#7]
Crawfish is one of the few clients to support webtorrent, but a common theme can be found among all the clients that do, lacking support for the usual torrent management.  In particular if you want to help host a file to web over torrent, taking from a torrent within the traditional torrent realm, it would be nice to not download every file.

It would especially be nice to have the UI features for managing it that we see in Qbittorrent and other standard desktop torrent clients including highlighting multiple files, sorting files by size, sorting files by completeness, sorting files by availability.  Technically the official webtorrent-desktop does support excluding a file but because it lacks those UI features if a torrent has 50 thousand jpgs in it it becomes impossible to manage, whereas in most desktop clients it isn't.

**Comment by drakonkat** [comment]
Great idea, I want to add for sure this basic torrent feature for now I was focusing on a wiki and clearing the code (In this way maybe other developer can contribute with some UI feature). After this I will handle this task

**Comment by drakonkat** [comment]
Hi, sorry for the late response I have added the feature that you were talking about. About the file "exclusion" I have added it expanding the list of file from the torrent and not during insertion (In my opinion , it's better to avoid annoying modal for the user every added torrent)

You can download the new update here: [1.7.16](https://github.com/drakonkat/Crawfish/releases/tag/v1.7.16-beta)
